// Generated by CoffeeScript 1.6.3
/*!
* windows-test.js: Tests for instances of the Windows transport
*
* (C) 2013 Joshua F. Rountree
# * MIT LICENSE
*
*/

var Transport, assert, assertInstall, assertLogs, assertWindows, helpers, path, transport, vows, winston;

path = require("path");

vows = require("vows");

assert = require("assert");

winston = require("winston");

helpers = require("winston/test/helpers");

Transport = require("../lib/winston-windows").Transport;

transport = new Transport();

assertInstall = function(transport) {};

assertWindows = function(transport) {
  assert.instanceOf(transport, Transport);
  return assert.isFunction(transport.log);
};

assertLogs = function() {
  var logger;
  transport = new winston.transports.Windows();
  logger = new winston.Logger({
    transports: [transport]
  });
  logger.log("info", "This is an INFORMATION test.");
  logger.log("warn", "This is an WARNING test.");
  return logger.log("error", "This is an ERROR test.");
};

vows.describe("winston-windows").addBatch({
  "An instance of the Windows Transport": {
    "should have the proper methods defined": function() {
      return assertWindows(transport);
    },
    "should log messages to Windows EventLog": function() {
      return assertLogs();
    }
  }
})["export"](module);
