// Generated by CoffeeScript 1.6.3
/*!
* windows-test.js: Tests for instances of the Windows transport
*
* (C) 2013 Joshua F. Rountree
# * MIT LICENSE
*
*/

var Windows, assert, assertWindows, closeTopic, helpers, path, transport, vows, winston;

assertWindows = function(transport) {
  assert.instanceOf(transport, Transport);
  return assert.isFunction(transport.log);
};

closeTopic = function() {
  var logger, transport;
  transport = new winston.transports.Windows();
  logger = new winston.Logger({
    transports: [transport]
  });
  logger.log("debug", "Test message to actually use socket");
  logger.remove({
    name: "Windows"
  });
  return transport;
};

path = require("path");

vows = require("vows");

assert = require("assert");

winston = require("winston");

helpers = require("winston/test/helpers");

Windows = require("../lib/winston-windows").Transport;

transport = new Windows();

vows.describe("winston-windows").addBatch({
  "An instance of the Windows Transport": {
    "should have the proper methods defined": function() {
      return assertWindows(transport);
    },
    "the log() method": helpers.testWindowsLevels(transport, "should log messages to Windows EventLog", function(ign, err, ok) {
      assert.isTrue(!err);
      assert.isTrue(ok);
      return assert.equal(transport.queue.length, 0);
    })
  }
})["export"](module);
