// Generated by CoffeeScript 1.6.3
var Service, config, svc;

Service = require("node-windows").Service;

config = require("../config");

svc = new Service({
  name: "WBX-WATCHDOG",
  description: "Watches for WBX billing files and handles transmission / encryption.",
  script: require("path").join(process.cwd(), "app.js"),
  env: {
    name: "NODE_ENV",
    value: process.env.NODE_ENV
  },
  env: {
    name: "WATCHDOG_HOME",
    value: process.cwd()
  }
});

svc.on("install", function() {
  return svc.start();
});

svc.on("alreadyinstalled", function() {
  return console.log("This service is already installed.");
});

svc.on("start", function() {
  return console.log(svc.name + " started!");
});

svc.install();
